### ISSUE TITLE
空指针问题

### ISSUE THREAD

**Issue by baonanhai** [limedroid/XRichText#5]
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.InputStream.read(byte[], int, int)' on a null object reference
                                                       at cn.droidlover.xrichtext.BaseImageLoader.readAndCloseStream(BaseImageLoader.java:77)
                                                       at cn.droidlover.xrichtext.BaseImageLoader.getBitmap(BaseImageLoader.java:47)
                                                       at cn.droidlover.xrichtext.XRichText$LocalImageGetter$1.run(XRichText.java:308)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by baonanhai** [comment]
我们把这个用在列表中,每一项都有这个.然后快速上下滑动,反复加载刷新的过程中出错程序崩溃.但是比较难出现这个问题,某些手机上可能出现比较容易.

**Comment by jackycaojiaqi** [comment]
项目已经不维护了吗？ @limedroid

**Comment by baonanhai** [comment]
估计是不维护了啊

**Comment by VergeDX** [comment]
Same issues here... I recommend this solution: [How to display HTML in TextView?](https://stackoverflow.com/questions/2116162/how-to-display-html-in-textview)
